-- Creating MUSIC ARTIST table--
CREATE TABLE MUSIC_ARTIST (
	ARTIST_ID INT AUTO_INCREMENT PRIMARY KEY,
    ARTIST_NAME VARCHAR(100),
    ORIGIN_CITY VARCHAR(50),
    GENRE_NAME ENUM('Rock', 'Jazz', 'Pop', 'Hip Hop', 'Country')
);

-- Creating MUSIC LABEL table--
CREATE TABLE MUSIC_LABEL (
	LABEL_ID INT AUTO_INCREMENT PRIMARY KEY,
    LABEL_NAME VARCHAR(75)
);

-- Creating MUSIC FORMAT table--
CREATE TABLE MUSIC_FORMAT (
	FORMAT_ID CHAR(1) PRIMARY KEY,
    FORMAT_NAME VARCHAR(50)
);

-- Creating MUSIC ALBUM table--
CREATE TABLE MUSIC_ALBUM (
	ALBUM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ALBUM_NAME VARCHAR(100),
    ARTIST_ID INT,
    RELEASE_DATE DATE,
	RECORDS_SOLD INT CHECK(RECORDS_SOLD < 1000000000),
    ORIGINAL_FORMAT CHAR(1),
    LABEL_ID INT,
    CONSTRAINT MUSIC_ALBUM_ARTIST_ID_FK FOREIGN KEY (ARTIST_ID) REFERENCES MUSIC_ARTIST(ARTIST_ID),
    CONSTRAINT MUSIC_ALBUM_FORMAT_FK FOREIGN KEY (ORIGINAL_FORMAT) REFERENCES MUSIC_FORMAT(FORMAT_ID),
    CONSTRAINT MUSIC_ALBUM_LABEL_FK FOREIGN KEY (LABEL_ID) REFERENCES MUSIC_LABEL(LABEL_ID)
);
