-- Inserting MUSIC ARTIST data --
INSERT INTO MUSIC_ARTIST(ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ("Nirvana", "Seattle, WA", "Rock");
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ("Miles Davis", "Alton, IL", "Jazz");
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ("Michael Jackson", "Gary, IN", "Pop");
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ("Lil' Wayne", "New Orleans, LA", "Hip Hop");
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ("Willie Nelson", "Abbott, TX", "Country");

-- Selecting all data from MUSIC ARTIST table --
SELECT *
FROM MUSIC_ARTIST;


-- Inserting MUSIC LABEL data --
INSERT INTO MUSIC_LABEL(LABEL_NAME)
VALUES("DGC Records");
INSERT INTO MUSIC_LABEL(LABEL_NAME)
VALUES("Columbia");
INSERT INTO MUSIC_LABEL(LABEL_NAME)
VALUES("Epic Records");
INSERT INTO MUSIC_LABEL(LABEL_NAME)
VALUES("Cash Money");

-- Selecting all data from MUSIC LABEL table --
SELECT *
FROM MUSIC_LABEL;


-- Inserting MUSIC FORMAT data --
INSERT INTO MUSIC_FORMAT(FORMAT_ID, FORMAT_NAME)
VALUES("V", "Vinyl");
INSERT INTO MUSIC_FORMAT(FORMAT_ID, FORMAT_NAME)
VALUES("T", "Cassette Tape");
INSERT INTO MUSIC_FORMAT(FORMAT_ID, FORMAT_NAME)
VALUES("C", "Compact Disc");
INSERT INTO MUSIC_FORMAT(FORMAT_ID, FORMAT_NAME)
VALUES("D", "Digital");

-- Selecting all data from MUSIC FORMAT table --
SELECT *
FROM MUSIC_FORMAT;

-- Inserting MUSIC ALBUM data --
INSERT INTO MUSIC_ALBUM (ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES ("Nevermind", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Nirvana'), '1991-09-23', 30000000, 'C', (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'DGC Records'));

INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES("In Utero", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Nirvana'), "1993-09-21", 15000000, "C", (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'DGC Records'));

INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES("Kind of Blue", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Miles Davis'), "1959-08-17", 4000000, "V", (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Columbia'));

INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES("Thriller", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Michael Jackson'), "1982-11-30", 65000000, "T", (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Epic Records'));

INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES("Bad", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Michael Jackson'), "1987-09-01", 45000000, "T", (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Epic Records'));

INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES("Tha Carter III", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = "Lil' Wayne"), "2008-06-09", 3800000, "D", (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Cash Money'));

INSERT INTO MUSIC_ALBUM(ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES("Red Headed Stranger", (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = 'Willie Nelson'), "1975-05-01", 2000000, "V", (SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME = 'Columbia'));

-- Selecting all data from MUSIC ALBUM table --
SELECT *
FROM MUSIC_ALBUM;
