-- Creating MUSIC GENRE table--
CREATE TABLE MUSIC_GENRE(
	GENRE_ID INT AUTO_INCREMENT PRIMARY KEY,
    GENRE_NAME VARCHAR(25)
);

-- Inserting MUSIC GENRE from MUSIC ARTIST table -- 
INSERT INTO MUSIC_GENRE(GENRE_NAME)
SELECT GENRE_NAME
FROM MUSIC_ARTIST;

-- Adds GENRE_ID column to MUSIC ARTIST table --
ALTER TABLE MUSIC_ARTIST 
ADD GENRE_ID INT;

-- Adds a foreign key restraint to GENRE_ID in the MUSIC_ARTIST table --
ALTER TABLE MUSIC_ARTIST
ADD CONSTRAINT MUSIC_ALBUM_GENRE_ID_FK FOREIGN KEY (GENRE_ID) REFERENCES MUSIC_GENRE(GENRE_ID);

-- Sets the GENRE_ID in the MUSIC_ARTIST table based on matching GENRE_NAME from the MUSIC_ARTIST and MUSIC_GENRE tables--
UPDATE MUSIC_ARTIST INNER JOIN MUSIC_GENRE ON MUSIC_ARTIST.GENRE_NAME = MUSIC_GENRE.GENRE_NAME SET MUSIC_ARTIST.GENRE_ID = MUSIC_GENRE.GENRE_ID;

-- Removes GENRE_NAME column --
ALTER TABLE MUSIC_ARTIST
DROP COLUMN GENRE_NAME;

-- Selecting all data from MUSIC ARTIST table --
SELECT *
FROM MUSIC_ARTIST;

-- Selecting all data from MUSIC GENRE table --
SELECT *
FROM MUSIC_GENRE;

-- Delete all albums from Lil'Wayne from MUSIC_ALBUM table --
DELETE FROM MUSIC_ALBUM WHERE ARTIST_ID = (SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME = "Lil' Wayne");

-- Delete Lil' Wayne from MUSIC_ARTIST table --
DELETE FROM MUSIC_ARTIST WHERE ARTIST_NAME = "Lil' Wayne";

-- Selecting all data from MUSIC ARTIST table --
SELECT *
FROM MUSIC_ARTIST;

