-- Dropping MUSIC_ALBUM, MUSIC_ARTIST, MUSIC_LABEL, MUSIC_FORMAT table --
DROP TABLE IF EXISTS MUSIC_ALBUM;
DROP TABLE IF EXISTS MUSIC_ARTIST;
DROP TABLE IF EXISTS MUSIC_GENRE;
DROP TABLE IF EXISTS MUSIC_LABEL;
DROP TABLE IF EXISTS MUSIC_FORMAT;